;;; AUTO GENERATED FILE
(ns clj-z3.core
  (:require [clj-z3.context :as context])
  (:require [clj-z3.expr :as expr])
  (:require [clj-z3.solver :as solver])
  (:gen-class))

;; NOTE: The following method is generated by hand
(defn z3-session
  "A Z3 session is a convenience wrapper around a Z3 context
  and a Z3 solver"
  []
  (let [c (context/context)
        s (.. c mkSolver)]
    {:ctx c :slv s}))
